use master
go

CREATE SERVER AUDIT TrackLogins
--TO APPLICATION_LOG;
TO FILE
(
 FILEPATH = 'D:\\MSSQL15.MSSQLSERVER\\MSSQL\audit',
 MAXSIZE = 200 MB,
 MAX_ROLLOVER_FILES=102,
 RESERVE_DISK_SPACE = OFF
)
WITH (QUEUE_DELAY = 5000, ON_FAILURE = CONTINUE)
GO

CREATE SERVER AUDIT SPECIFICATION TrackAllLogins
FOR SERVER AUDIT TrackLogins
  ADD (FAILED_LOGIN_GROUP),
  ADD (SUCCESSFUL_LOGIN_GROUP),
  ADD (AUDIT_CHANGE_GROUP)
WITH (STATE = ON);
GO

ALTER SERVER AUDIT TrackLogins
WITH (STATE = ON);
GO

