{
 "title": "SQLDBATools",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Page Life Expectancy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT /* Grafana => PLE */ top 1 collection_time as time, page_life_expectancy FROM DBA.dbo.dm_os_performance_counters ORDER BY collection_time desc;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select top 1 master.dbo.local2utc(collection_time) as time,\tsystem_cpu_utilization as CPU from DBA..dm_os_ring_buffers order by time DESC"
    }
   ]
  },
  {
   "title": "Active Request",
   "type": "stat",
   "description": "--\tQuery to find what's is running on server\nSELECT\ts.session_id, \n\t\tDB_NAME(r.database_id) as DBName,\n\t\tr.percent_complete,\n\t\t[session_status] = s.status,\n\t\t[request_status] = r.status,\n\t\t[running_command] = r.command,\n\t\t[request_wait_type] = r.wait_type, \n\t\t[request_wait_resource] = wait_resource,\n\t\t[request_start_time] = r.start_time,\n\t\t[request_running_time] = CAST(((DATEDIFF(s,r.start_time,GetDate()))/3600) as varchar) + ' hour(s), '\n\t\t\t+ CAST((DATEDIFF(s,r.start_time,GetDate())%3600)/60 as varchar) + 'min, '\n\t\t\t+ CAST((DATEDIFF(s,r.start_time,GetDate())%60) as varchar) + ' sec',\n\t\t[est_time_to_go] = CAST((r.estimated_completion_time/3600000) as varchar) + ' hour(s), '\n\t\t\t\t\t\t+ CAST((r.estimated_completion_time %3600000)/60000  as varchar) + 'min, '\n\t\t\t\t\t\t+ CAST((r.estimated_completion_time %60000)/1000  as varchar) + ' sec',\n\t\t[est_completion_time] = dateadd(second,r.estimated_completion_time/1000, getdate()),\n\t\t[blocked by] = r.blocking_session_id,\n\t\t[statement_text] = Substring(st.TEXT, (r.statement_start_offset / 2) + 1, (\n\t\t\t\t(\n\t\t\t\t\tCASE r.statement_end_offset\n\t\t\t\t\t\tWHEN - 1\n\t\t\t\t\t\t\tTHEN Datalength(st.TEXT)\n\t\t\t\t\t\tELSE r.statement_end_offset\n\t\t\t\t\t\tEND - r.statement_start_offset\n\t\t\t\t\t) / 2\n\t\t\t\t) + 1),\n\t\t[Batch_Text] = st.text,\n\t\t[WaitTime(S)] = r.wait_time / (1000.0),\n\t\t[total_elapsed_time(S)] = r.total_elapsed_time / (1000.0),\n\t\ts.login_time, s.host_name, s.host_process_id, s.client_interface_name, s.login_name, \n\t\ts.memory_usage, \n\t\t[session_writes] = s.writes, \n\t\t[request_writes] = r.writes, \n\t\t[session_logical_reads] = s.logical_reads, \n\t\t[request_logical_reads] = r.logical_reads, \n\t\ts.is_user_process, \n\t\t[session_row_count] = s.row_count,\n\t\t[request_row_count] = r.row_count,\n\t\tr.sql_handle, \n\t\tr.plan_handle, \n\t\tr.open_transaction_count,\n\t\t[request_cpu_time] = r.cpu_time,\n\t\t[granted_query_memory] = CASE WHEN ((CAST(r.granted_query_memory AS numeric(20,2))*8)/1024/1024) >= 1.0\n\t\t\t\t\t\t\t\t\t  THEN CAST(((CAST(r.granted_query_memory AS numeric(20,2))*8)/1024/1024) AS VARCHAR(23)) + ' GB'\n\t\t\t\t\t\t\t\t\t  WHEN ((CAST(r.granted_query_memory AS numeric(20,2))*8)/1024) >= 1.0\n\t\t\t\t\t\t\t\t\t  THEN CAST(((CAST(r.granted_query_memory AS numeric(20,2))*8)/1024) AS VARCHAR(23)) + ' MB'\n\t\t\t\t\t\t\t\t\t  ELSE CAST((CAST(r.granted_query_memory AS numeric(20,2))*8) AS VARCHAR(23)) + ' KB'\n\t\t\t\t\t\t\t\t\t  END,\n\t\tr.query_hash, \n\t\tr.query_plan_hash,\n\t\t[BatchQueryPlan] = bqp.query_plan,\n\t\t[SqlQueryPlan] = CAST(sqp.query_plan AS xml),\n\t\t[program_name] = CASE\tWHEN\ts.program_name like 'SQLAgent - TSQL JobStep %'\n\t\t\t\tTHEN\t(\tselect\ttop 1 'SQL Job = '+j.name \n\t\t\t\t\t\t\tfrom msdb.dbo.sysjobs (nolock) as j\n\t\t\t\t\t\t\tinner join msdb.dbo.sysjobsteps (nolock) AS js on j.job_id=js.job_id\n\t\t\t\t\t\t\twhere right(cast(js.job_id as nvarchar(50)),10) = RIGHT(substring(s.program_name,30,34),10) \n\t\t\t\t\t\t)\n\t\t\t\tELSE\ts.program_name\n\t\t\t\tEND,\n\t\t[IsSqlJob] = CASE WHEN s.program_name like 'SQLAgent - TSQL JobStep %'THEN 1 ELSE 2\tEND\n\t\t,open_resultset_count\nFROM\tsys.dm_exec_sessions AS s\nLEFT JOIN sys.dm_exec_requests AS r ON r.session_id = s.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS st\nOUTER APPLY sys.dm_exec_query_plan(r.plan_handle) AS bqp\nOUTER APPLY sys.dm_exec_text_query_plan(r.plan_handle,r.statement_start_offset, r.statement_end_offset) as sqp\nWHERE\ts.session_id != @@SPID\n\tAND (\t(CASE\tWHEN\ts.session_id IN (select ri.blocking_session_id from sys.dm_exec_requests as ri )\n\t\t\t\t\t--\tGet sessions involved in blocking (including system sessions)\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t\tOR\n\t\t\t(CASE\tWHEN\ts.session_id > 50\n\t\t\t\t\t\t\tAND r.session_id IS NOT NULL -- either some part of session has active request\n\t\t\t\t\t\t\tAND ISNULL(open_resultset_count,0) > 0 -- some result is open\n\t\t\t\t\t\t\tAND NOT (s.status = 'sleeping' AND r.status IN ('background','sleeping'))\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t\tOR\n\t\t\t(CASE\tWHEN\ts.session_id > 50\n\t\t\t\t\t\t\tAND ISNULL(r.open_transaction_count,0) > 0\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t)\t\t\nORDER BY [request_start_time];",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": ";WITH T_Active_Requests AS\n(\n--\tQuery to find what's is running on server\nSELECT\ts.session_id\nFROM\tsys.dm_exec_sessions AS s\nLEFT JOIN sys.dm_exec_requests AS r ON r.session_id = s.session_id\nOUTER APPLY sys.dm_exec_sql_text(r.sql_handle) AS st\nOUTER APPLY sys.dm_exec_query_plan(r.plan_handle) AS bqp\nOUTER APPLY sys.dm_exec_text_query_plan(r.plan_handle,r.statement_start_offset, r.statement_end_offset) as sqp\nWHERE\ts.session_id != @@SPID\n\tAND (\t(CASE\tWHEN\ts.session_id IN (select ri.blocking_session_id from sys.dm_exec_requests as ri )\n\t\t\t\t\t--\tGet sessions involved in blocking (including system sessions)\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t\tOR\n\t\t\t(CASE\tWHEN\ts.session_id > 50\n\t\t\t\t\t\t\tAND r.session_id IS NOT NULL -- either some part of session has active request\n\t\t\t\t\t\t\tAND ISNULL(open_resultset_count,0) > 0 -- some result is open\n\t\t\t\t\t\t\tAND NOT (s.status = 'sleeping' AND r.status IN ('background','sleeping'))\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t\tOR\n\t\t\t(CASE\tWHEN\ts.session_id > 50\n\t\t\t\t\t\t\tAND ISNULL(r.open_transaction_count,0) > 0\n\t\t\t\t\tTHEN\t1\n\t\t\t\t\tELSE\t0\n\t\t\tEND) = 1\n\t\t)\t\t\n)\nSELECT SYSUTCDATETIME() as time, COUNT(*) as Counts\nFROM T_Active_Requests"
    }
   ]
  },
  {
   "title": "Memory Grants Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select top 1 collection_time as time, memory_grants_pending from DBA.[dbo].[dm_os_performance_counters] order by collection_time desc"
    }
   ]
  },
  {
   "title": "Available MBytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select top 1 collection_time as time, cast(available_physical_memory_gb*1024 as decimal(20,0)) as available_physical_memory from DBA.[dbo].[dm_os_sys_memory] order by collection_time desc"
    }
   ]
  },
  {
   "title": "SqlServer Max M/r Usage",
   "type": "gauge",
   "description": "Ratio of Total Server Memory to Target Server Memory",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select top 1 collection_time as time, cast((total_server_memory_mb*100.0)/target_server_memory_mb as decimal(20,0)) as max_memory_utilization from DBA.[dbo].[dm_os_performance_counters] order by collection_time desc"
    }
   ]
  },
  {
   "title": "SqlServer Physical Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select top 1 collection_time as time, cast(([SQL Server Memory Usage (MB)]*1.0)/1024 as decimal(20,2)) as SqlServer_Physical_Memory_GB from DBA.[dbo].[dm_os_process_memory] order by collection_time desc"
    }
   ]
  },
  {
   "title": "Blocked Sessions",
   "type": "stat",
   "description": "select count(*) as counts from sys.sysprocesses as p where p.blocked <> 0",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as counts from sys.sysprocesses as p where p.blocked <> 0"
    }
   ]
  },
  {
   "title": "Active User Requests",
   "type": "graph",
   "description": "https://sqlperformance.com/2014/10/sql-performance/knee-jerk-page-life-expectancy",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": ";with t_active_results as \r\n(\tselect collection_time, count(*) as active_requests \r\n\tfrom DBA.dbo.WhoIsActive_ResultSets\r\n\twhere collection_time BETWEEN master.dbo.utc2local($__timeFrom()) AND master.dbo.utc2local($__timeTo())\r\n\tgroup by collection_time\r\n)\r\nselect master.dbo.local2utc(collection_time) as [time], active_requests \r\nfrom t_active_results\r\norder by [time]"
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "graph",
   "description": "https://sqlperformance.com/2014/10/sql-performance/knee-jerk-page-life-expectancy",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  master.dbo.local2utc(collection_time) as time,\n  page_life_expectancy\nFROM\n  DBA.dbo.dm_os_performance_counters\nWHERE \n  collection_time BETWEEN master.dbo.utc2local($__timeFrom()) AND master.dbo.utc2local($__timeTo())\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "SqlServer: Page Faults",
   "type": "graph",
   "description": "https://sqlperformance.com/2014/10/sql-performance/knee-jerk-page-life-expectancy",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "\n;with t_page_faults as\n(\n\tselect collection_time, page_fault_count, LAG(page_fault_count) OVER ( ORDER BY collection_time ) as page_fault_count__prev\n\t\t\t,LAG(collection_time) OVER ( ORDER BY collection_time ) as collection_time_prev\t\t\t\n\tfrom DBA.[dbo].[dm_os_process_memory] \n\twhere collection_time BETWEEN master.dbo.utc2local($__timeFrom()) AND master.dbo.utc2local($__timeTo())\n)\nselect\tmaster.dbo.local2utc(collection_time) as time, --page_fault_count, DATEDIFF(second,collection_time_prev,collection_time) as interval_seconds,\n\t\tpage_faults_in_interval =\n\t\t(case when page_fault_count__prev is null then 0\n\t\t\t when page_fault_count < page_fault_count__prev then page_fault_count\n\t\t\t when page_fault_count >= page_fault_count__prev then page_fault_count-page_fault_count__prev\n\t\t\t else null\n\t\t\t end)\nfrom t_page_faults\norder by time asc"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "https://sqlperformance.com/2014/10/sql-performance/knee-jerk-page-life-expectancy",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "% CPU" }
   ],
   "targets": [
    {
     "rawSql": "select /* Grafana => CPU */\n\t\tmaster.dbo.local2utc(collection_time) as time,\n\t\tsystem_cpu_utilization as OS,\n\t\tsql_cpu_utilization as [SqlServer]\nfrom DBA..dm_os_ring_buffers\nwhere collection_time BETWEEN master.dbo.utc2local($__timeFrom()) AND master.dbo.utc2local($__timeTo())\norder by time asc"
    }
   ]
  },
  {
   "title": "Server Load Counter",
   "type": "graph",
   "description": "https://sqlperformance.com/2014/10/sql-performance/knee-jerk-page-life-expectancy",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": ";WITH T_Metrics AS (\r\n\tSELECT /* SQLWATCH - Overview => SQL Server Activity */\r\n\t\t  [time] = snapshot_time\r\n\t\t  ,metric = [counter_name]\r\n\t\t  ,[value] = FLOOR([cntr_value_calculated])\r\n\tFROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\r\n\tWHERE $__timeFilter(snapshot_time)\r\n\t  AND counter_name IN ('Batch Requests/sec','Logins/sec','Transactions/sec','User Connections','SQL Compilations/sec','SQL Re-Compilations/sec')\r\n\t  AND [sql_instance] = 'MSI'\r\n)\r\nSELECT time, [Batch Requests/sec],[Logins/sec],[SQL Compilations/sec],[SQL Re-Compilations/sec],[Transactions/sec],[User Connections]\r\nFROM T_Metrics as up\r\nPIVOT (MAX([value]) FOR metric IN ([Batch Requests/sec],[Logins/sec],[SQL Compilations/sec],[SQL Re-Compilations/sec],[Transactions/sec],[User Connections])) as pvt\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "User Session Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select cast(master.dbo.local2utc([collection_time]) as smalldatetime) as [time],[dd hh:mm:ss.mss],[login_name],[wait_info],CAST(REPLACE([CPU],',','') AS BIGINT) as [CPU],CAST(REPLACE([reads],',','') AS BIGINT) as reads,CAST(REPLACE([writes],',','') AS BIGINT) as [writes],CAST(REPLACE([used_memory],',','') AS BIGINT) as [used_memory],[host_name],[database_name],[program_name],[sql_command]\r\nfrom DBA.dbo.WhoIsActive_ResultSets\r\nwhere collection_time BETWEEN master.dbo.utc2local($__timeFrom()) AND master.dbo.utc2local($__timeTo())\r\norder by [time] desc, [TimeInMinutes] desc"
    }
   ]
  }
 ]
}